import Contact from '@/components/Contact'

import React from 'react'

const Page = () => {
  return (
    <div>
      <Contact></Contact>
    </div>
  )
}

export default Page

export const metadata = {
    title: "Contact Page",
    description: "Generated by create next app",
  };
  