import Desc from "@/components/Desc";
import Image from "next/image";


export default function Home() {

 
  return (
  <>
   <Desc></Desc>
  </>
  );
}
export const metadata = {
  title: "FORD-Cobra",
  description: "Generated by create next app",
};

